# Ejemplos básicos de Numpy

Numpy es un paquete de propósito general para procesar arrays y para cálculos científicos.

A la hora de hacer una lista con `float` usando `range`, obtenemos un error:

In [2]:
range(1.,3.) #Produce un error

TypeError: 'float' object cannot be interpreted as an integer

También cuando manejamos listas desde un punto de vista matemático volvemos a tener problemas

In [4]:
l1=[1,2,3]
l2=[3,4,5]

In [33]:
l1*l2 #Esto nos va a dar un error

TypeError: can't multiply sequence by non-int of type 'list'

También trabajar con una lista como si fuera una matriz... no es lo más recomendable:

In [36]:
mymatrix=[[1,2,3],[3,1,2],[1,3,2]]
mymatrix[:][1] # La segunda fila

[3, 1, 2]

Ahora vamos a cargar el paquete `numpy`

In [2]:
import numpy as np

In [2]:
l1=[1,2,3]
l2=[3,4,5]

arr1=np.array(l1)
arr2=np.array(l2)

arr1*arr2 # Esto sí que funciona

array([ 3,  8, 15])

Los arrays pueden ser matrices (de diferente tamaño y forma)

In [3]:
A = np.array([[1,2,3],[3,1,2],[1,3,2]])

Y tenemos muchas funciones para realizar todo tipo de cálculos

In [4]:
A.ndim # Es una matriz de dos dimensiones

2

In [5]:
A.shape # Es una matriz 3x3

(3, 3)

In [6]:
A.size # En número de entradas totales

9

### Matrices

Los más básicos son zeros o todos sus elementos iguales

In [7]:
np.zeros((2,3)) # Una matriz 2x3 de ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

También una matriz de 1s

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.full((2,3),1,dtype='float') # Una matriz 2x3 de 1. (en float)

array([[1., 1., 1.],
       [1., 1., 1.]])

También la matriz identidad y otras matrices

In [10]:
np.identity(3) # La matriz identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

El acceso a los elementos del array se parece mucho a las de las listas, aunque en este caso no tenemos que hacer `A[1][:]`

In [11]:
A[1,:] # Segunda fila (¡ojo con la numeración! Python comienza en 0).

array([3, 1, 2])

In [17]:
A[:2,1] # De la segunda columna 

array([2, 1])

**EJERCICIO:** ¿Cómo haríamos para obtener una submatriz? ¿Cómo podríamos obtener un menor de una matriz?

Como antes, podemos escribir una matriz a través de `np.array`

In [4]:
A = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(A)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


### Operaciones básicas

In [43]:
A-2 # Restamos 2 a cada elemento de la matriz

array([[-1,  0,  1],
       [ 1, -1,  0],
       [-1,  1,  0]])

In [44]:
A*0.5 # Multiplicamos por 0.5

array([[0.5, 1. , 1.5],
       [1.5, 0.5, 1. ],
       [0.5, 1.5, 1. ]])

In [50]:
B = np.identity(3)

In [49]:
A+B # Suma de las dos matrices

array([[2., 2., 3.],
       [3., 2., 2.],
       [1., 3., 3.]])

In [58]:
np.dot(A,B) # Producto matricial 

array([[1., 2., 3.],
       [3., 1., 2.],
       [1., 3., 2.]])

In [60]:
A*B # Este *no* es el producto matricial, es el producto elemento a elemento.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

In [64]:
A.transpose() # Traspuesta de la matriz A

array([[1, 3, 1],
       [2, 1, 3],
       [3, 2, 2]])

In [65]:
np.transpose(A) # La trasposición de una matriz puede obtenerse de este otro modo

array([[1, 3, 1],
       [2, 1, 3],
       [3, 2, 2]])

Algunas operaciones especiales. En algunos casos necesitaremos la intercesión del 'subpaquete' *linalg*


In [68]:
np.linalg.det(A) # Calculamos el determinante. No funciona np.det(A)

12.000000000000005

In [66]:
np.trace(A) # La traza de la matriz. También vale np.linalg.trace(A)

4

In [70]:
np.linalg.inv(A) # La matriz inversa de A. No existe la función np.inv(A)

array([[-0.33333333,  0.41666667,  0.08333333],
       [-0.33333333, -0.08333333,  0.58333333],
       [ 0.66666667, -0.08333333, -0.41666667]])

In [71]:
np.dot(np.linalg.inv(A),A)

array([[ 1.00000000e+00, -6.93889390e-17, -1.94289029e-16],
       [ 1.11022302e-16,  1.00000000e+00,  2.22044605e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00]])

In [74]:
b=np.array([1,1,1]) # Un vector
x=np.linalg.solve(A,b) # Solución a la ecuación $Ax=b$

In [75]:
np.dot(A,x)

array([1., 1., 1.])

Para más información: https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html